### ISSUE TITLE
Setup Repo

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#1]
Setup initial repository structure using Cookiecutter project template. Setup includes creating a requirements file to list necessary dependencies and configuring environment variables to ensure the development environment is properly set up. 

- [X] Add Cookiecutter project template
- [X] Create Requirements File
- [X] Configure environment variables
- [x] Migrate to Poetry for easier reproducible environments
  - [X] Need to add new dependencies such as airbyte
  - [ ] Try listing only core dependencies in `pyproject.toml`
- [X] Test setup in a clean environment
- [ ] Update README with setup instructions
  - [ ] List required dependencies in the README for anyone looking to setup a dev environment on their own machine

**Comment by wtfsayo** [comment]
@santteegt I added poetry config; I also tested it in new environment but can you also test it on your own machine!!!

**Comment by santteegt** [comment]
TODOs:
- Need to add new dependencies such as airbyte
- Docker configuration should be prioritized
- List requires dependencies in the README for anyone looking to setup a dev environment on their own machine

**Comment by wtfsayo** [comment]
> TODOs:
> 
> * Need to add new dependencies such as airbyte
> * Docker configuration should be prioritized
> * List requires dependencies in the README for anyone looking to setup a dev environment on their own machine

can we add these to top post as pending todos @earth2travis
