### ISSUE TITLE
1.4 Implement Data Chunking

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#10]
Implement data chunking to divide the normalized data into smaller, more manageable pieces. Data chunking facilitates efficient processing and embedding of large datasets. By breaking down the data into chunks, the system can handle the data more effectively, ensuring better performance and scalability.

- [X] Update Custom parser
- [X] Perform data analysis on results
- [X] Identify parameters for tunning the process

**Comment by santteegt** [comment]
Still pending:
- Do some data exploration on the discourseTopicPosts endpoint
- Validate the full data pipeline using the discourseTopicPosts endpoint

**Comment by santteegt** [comment]
To consider in #22:

- How to tie `discourseTopics` with `discourseTopicPosts` at the airbyte manifest level
