### ISSUE TITLE
1.7 Integrate Gaia Embedding Models

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#12]
Integrate the Gaia embedding models into the pipeline to generate vector embeddings from the parsed data. This involves configuring the models to accept the structured data and output vector representations that can be stored in the knowledge base. Proper integration of the Gaia embedding models is essential for creating a high-quality, searchable vector database that enhances the functionality of AI agents.

- [X] Identify public GAIA node and embedding model for dev/testing
- [X] Implement custom Embedder UDF capable of connecting to a GAIA node
- [X] Identify parameters for tunning execution through parallelization
- [X] Connect embedded into the pipeline

**Comment by santteegt** [comment]
To consider in #21:
- Do some stress testing with all extracted records to see if there's any possibility of parallelization
