### ISSUE TITLE
1.8 Explore Output Connector

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#13]
Research options for implementing an output connector to export the generated knowledge base to Qdrant. The goal is to identify the best practices and available tools for efficiently transferring data to Qdrant's vector database. This exploration lays the groundwork for developing a robust and effective output connector, ensuring that the knowledge base is accurately and securely stored in Qdrant.

- [x] Explore Qdrant documentation
- [x] Eval how to implement a new output connector for Pathway that integrates Qdrant vector store
- [x] Explore how qdrant vector store is integrated and configured within a gaianet node

**Comment by santteegt** [comment]
Docs on how to write a custom Python output connector in Pathway
- https://pathway.com/developers/user-guide/connect/connectors/python-output-connectors

We'll use `qdrant-client` python library for interacting with qdrant db
- https://qdrant.tech/documentation/quickstart/
