### ISSUE TITLE
2.0.1 Implement Output Connector

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#14]
Develop the output connector to facilitate the export of the generated knowledge base to Qdrant. The output connector will handle the data transfer process, ensuring that the vector embeddings and associated metadata are correctly formatted and securely transmitted. Implementing this connector is crucial for maintaining the integrity and accessibility of the knowledge base within the Qdrant vector store.

Related to #13

**Comment by santteegt** [comment]
Successfully implemented the QdrantDBVectorStore class and connected to the experimental pipeline:
- stores generated embedding with metadata
- generate a snapshot at the end of the process
