### ISSUE TITLE
2.0.3 Integrate with Gaia node Qdrant Vector Store

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#15]
Integrate the output connector with the Qdrant vector store. This involves configuring the connector to communicate with Qdrant's API, ensuring seamless data ingestion and storage. Proper integration is essential for enabling efficient retrieval and querying of the knowledge base within Qdrant, enhancing the performance and usability of the AI agents.

**Comment by santteegt** [comment]
Related to #14

**Comment by santteegt** [comment]
Output connector is working as expected. Just need to make sure in #30 we use `qdrant/qdrant:v1.10.1` image (the gaia node uses this version. Got errors when trying to import a snapshot generated with a newer version) so it maintains version compatibility between dev end production environments
