### ISSUE TITLE
2.0.2 Export Knowledge Base Snapshot

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#16]
Execute export process to generate and store a snapshot of the knowledge base in Qdrant. This includes validating the data export to ensure completeness and accuracy, as well as performing any necessary post-export checks. Successfully exporting the knowledge base snapshot is vital for preserving a reliable and up-to-date repository of information that can be utilized by AI agents and other applications.

This process should be automated in the pipeline.

Resources:
- How to generate a vector snapshot ((link)[https://docs.gaianet.ai/creator-guide/knowledge/text#create-a-vector-snapshot])

**Comment by santteegt** [comment]
Solved in #14
