### ISSUE TITLE
2.1.3 Decide on LLM Embedding Model

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#17]
Select appropriate LLM embedding model for the Gaia node. The chosen model should be compatible with the data structure and use case of the project, ensuring optimal performance and accuracy. The decision-making process will include evaluating different models based on criteria such as embedding quality, processing speed, and resource requirements.

**Comment by wtfsayo** [comment]
Got KT from @santteegt, started on this as well!!

**Comment by wtfsayo** [comment]
Waiting for output connector / pipeline to be working from @santteegt !!!
then can do local testing for most compatible model

**Comment by santteegt** [comment]
The output connector is ready for testing. Here are some instructions on how to use it with gaia:
- Open the `data_explore.ipynb` notebook
- Run a local qdrant instance using docker (just for embeddings + snapshot generation):
```
docker run -p 6333:6333 -p 6334:6334 -v ./qdrant_dev:/qdrant/storage:z qdrant/qdrant:v1.10.
```
- For testing purposes enable the http input connector (omit the airbyte connector cells) to extract the first page from the proposals endpoint
- Execute the rest of the pipeline using this input data
- Download the snapshot file using the URL displayed at the end of the pipeline execution and save it on the `gaianet` folder (e.g. "boardroom_test-xxxxxx.....snapshot")
- Shutdown the qdrant docker instance
- On the gaia node side, the config file should have the following updates:

```
{
  ...
  "embedding_collection_name": "boardroom_test",
  "embedding_ctx_size": "768",
  ...
  "snapshot": "boardroom_test-xxxxxx.....snapshot",
  ....
}
```
- run `gaia init` and `gaia start`

**Comment by wtfsayo** [comment]
Data doesn't get inserted into qdrant vector db!!! Can you share the Jupyter notebook with cleanup stuff!!!

**Comment by santteegt** [comment]
@wtfsayo https://github.com/raid-guild/gaianet-rag-api-pipeline/blob/main/experiments/data_explore_cftoc.ipynb just click run all cells

**Comment by wtfsayo** [comment]
Still nothing got inserted to vector store @santteegt, is it working on your machine?

**Comment by santteegt** [comment]
@wtfsayo yes. It's been working for me all the time. What error are you getting?

**Comment by wtfsayo** [comment]
Started to work now!

**Comment by wtfsayo** [comment]
> The output connector is ready for testing. Here are some instructions on how to use it with gaia:
> 
> * Open the `data_explore.ipynb` notebook
> * Run a local qdrant instance using docker (just for embeddings + snapshot generation):
> 
> ```
> docker run -p 6333:6333 -p 6334:6334 -v ./qdrant_dev:/qdrant/storage:z qdrant/qdrant:v1.10.
> ```
> 
> * For testing purposes enable the http input connector (omit the airbyte connector cells) to extract the first page from the proposals endpoint
> * Execute the rest of the pipeline using this input data
> * Download the snapshot file using the URL displayed at the end of the pipeline execution and save it on the `gaianet` folder (e.g. "boardroom_test-xxxxxx.....snapshot")
> * Shutdown the qdrant docker instance
> * On the gaia node side, the config file should have the following updates:
> 
> ```
> {
>   ...
>   "embedding_collection_name": "boardroom_test",
>   "embedding_ctx_size": "768",
>   ...
>   "snapshot": "boardroom_test-xxxxxx.....snapshot",
>   ....
> }
> ```
> 
> * run `gaia init` and `gaia start`

going to try this now!! (with llama3-8b)
