### ISSUE TITLE
2.1.2 Explore Node Configurations in Gaia

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#18]
Research and understanding the various configuration options available for Gaia nodes. The goal is to identify the optimal settings and configurations that will support the project's requirements, including data processing, storage, and retrieval. This exploration is crucial for ensuring that the Gaia node is set up correctly and operates efficiently within the pipeline.

Resources:
- Guide on how to customize a gaia node ([link](https://docs.gaianet.ai/node-guide/customize/))
- Node config recipes ([link](https://github.com/GaiaNet-AI/node-configs))

**Comment by wtfsayo** [comment]
Starting on this

**Comment by wtfsayo** [comment]
parallel to #17
