### ISSUE TITLE
1.1 Implement Pipeline Entrypoint Modules

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#2]
Setup foundational components of the pipeline. Build a base HTTP connector to enable communication with external APIs and creating an API key for accessing the Boardroom Governance API. These steps are crucial for establishing the pipeline's initial data retrieval capabilities, ensuring the system can securely and efficiently fetch the necessary data from the Boardroom API.

- [X] Build base HTTP connector 
- [ ] Create API key for Boardroom
- [X] Define base schema for API data extraction

**Comment by earth2travis** [comment]
Still within the request limit of the public API key

**Comment by santteegt** [comment]
Once the pipeline is completely built, we need to run a complete process through all relevant endpoints

**Comment by santteegt** [comment]
Completed in #5
