### ISSUE TITLE
2.1.4 Plug Gaia Node into Pipeline

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#20]
Integrate the Gaia node with the data pipeline. The connection should enable seamless data flow between the pipeline and the node, ensuring that the processed data can be embedded and stored efficiently. Successful integration is essential for maintaining the integrity and performance of the entire system.

**Comment by santteegt** [comment]
Some progress on this has already been done at the data pipeline level in #12

**Comment by wtfsayo** [comment]
@santteegt would recommend using `phi3-mini-4k-instruct` as output model, its the most available model on gaianet 
[See here](https://www.gaianet.ai/network-map)
