### ISSUE TITLE
2.2.3 Optimize Parsing Logic

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#22]
Refine and optimizing the parsing logic used in the data pipeline. Based on the results from testing, adjustments may be needed to improve the accuracy and efficiency of data extraction and transformation. Tweaking the parsing logic ensures that the pipeline produces high-quality, consistent data for embedding and storage.

**Comment by earth2travis** [comment]
Related to: https://github.com/raid-guild/gaianet-rag-api-pipeline/issues/21

**Comment by santteegt** [comment]
Introdced some optimizations in 55f5317f1261ded640a42ae1887dd082678d4ce5
