### ISSUE TITLE
Update OpenAPI Specification

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#23]
https://swagger.boardroom.info/#/

The spec they gave us is not complete. They made it by hand or generated it. But it does not include some of the request parameters we need. Some sections are missing and there are errors that need to be manually fixed.

Some of what we thought was missing is actually at the bottom of the page. We need to identify if there is anything else missing and update the YAML file.

- [ ] Load spec into postman/swagger ui
- [ ] test endpoint definitions
- [ ] fix missing info
- [ ] export collection and use existing tooling for converting output into openapi spec ([link](https://www.postman.com/postman/postman-open-technologies-convert-postman-collections-into-openapi/overview))

**Comment by earth2travis** [comment]
- Sayonora identified the endpoints from Boardroom
- The spec we were provided is missing endpoints
- Writing this spec is outside of the scope of what we estimated
- Were expecting this to function out of the box
- Endpoint does not have the protocol ID
- Are having to make adjustments in Postman
- Should we ask Gaianet to ask Boardroom for a complete spec?
- They most likely made it by hand or just exported it with Swagger
- We can go through the endpoints and fill in the missing parameters and update the spec
- When you export the collection from Postman you can convert it to the OpenAPI spec
- This is two days of development work
- We need an additional quote for this effort

**Comment by wtfsayo** [comment]
halfway there with #32

**Comment by wtfsayo** [comment]
> halfway there with [#32](https://github.com/raid-guild/gaianet-rag-api-pipeline/pull/32)

@santteegt should be already unblocked as of #32 being merged

**Comment by wtfsayo** [comment]
### Proposal and Discussion Related
- [x] `/protocols/{cname}`
- [x] `/protocols/{cname}/proposals`
- [x] `/proposals/{refId}/votes`
- [x] `/discourseCategories?protocol={cname}`
- [x] `/discourseTopics?protocol={cname}`
- [x] `/discourseTopicPosts?protocol={cname}`
- [x] `/protocols/{cname}/voters`

### Voter Data
- [x] `/protocols/{cname}/voters`
- [x] `/voters/{address}/votes` (doesn't work as described on docs)

### Delegate Data
- [x] `/delegates/getDelegatorsByProtocol/{protocol}`
- [x] `/delegates/{address}/getDelegatorCount`
- [ ] `/getDelegationPitch/{protocol}`

**Comment by wtfsayo** [comment]
added following endpoints in total to cleaned openapi spec

- [x] `/protocols`
- [x] `/protocols/{cname}`
- [x] `/protocols/{cname}/proposals`
- [x] `/proposals`
- [x] `/proposals/{refId}`
- [x] `/proposals/{refId}/votes`
- [x] `/proposals/{refId}/pendingVotes`
- [x] `/voters/{address}/votes`
- [x] `/discourseTopics`
- [x] `/discourseCategories`
- [x] `/discourseTopicPosts`
- [x] `/protocols/{cname}/voters`
- [x] `/delegates/getDelegatorsByProtocol/{cname}`
- [x] `/delegates/{address}/getDelegatorCount`
- [x] `/getDelegationPitchesByProtocol/{protocol}` // API not good returns only limited results
- [x] `/getDelegationPitch/{protocol}/{address}`

**Comment by santteegt** [comment]
@wtfsayo please help me including the missing `/delegates/getDelegatedVotingPowerByProtocol/{cname}` endpoint to the spec.

Also pushes a couple quick fixes in 3e9f36e9a860d89b0af30f52a204912e34168d60

**Comment by wtfsayo** [comment]
@santteegt added

**Comment by santteegt** [comment]
Added some final minor fixes and validated the open API spec in #4
