### ISSUE TITLE
2.0.4 Implement CLI interface

### ISSUE THREAD

**Issue by santteegt** [raid-guild/gaianet-rag-api-pipeline#29]
Implement a command-line interface for users to specify config parameters and run the full pipeline.

- [x] Identify good libraries to use
- [x] Collect and define data pipeline setup parameters
- [x] Implement cli entrypoint
- [ ] Run tests

Libraries:
- click ([link](https://click.palletsprojects.com/en/8.1.x/))

Resources:
- https://simonwillison.net/2023/Sep/30/cli-tools-python/
- https://realpython.com/python-click/

**Comment by wtfsayo** [comment]
Went through `click` docs; Should be smooth!!!
