### ISSUE TITLE
Identify Relevant Data Points

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#3]
Determine which data points from the Boardroom Governance API are relevant for Aave DAO. This includes reviewing the available API endpoints and deciding which pieces of data are necessary for creating a comprehensive and useful knowledge base. Identifying these data points is essential for ensuring that the pipeline extracts all relevant information needed for subsequent processing and analysis.

**Comment by wtfsayo** [comment]
### Proposal and Discussion Related
- [x] `/protocols/{cname}`
- [x] `/protocols/{cname}/proposals`
- [ ] `/proposals/{refId}/votes`
- [x] `/discourseCategories?protocol={cname}`
- [x] `/discourseTopics?protocol={cname}`
- [x] `/discourseTopicPosts?protocol={cname}`

### Voter Data
- [x] `/protocols/{cname}/voters`
- [ ] `/voters/{address}/votes` (doesn't work as described on docs)

### Delegate Data
- [x] `/delegates/getDelegatorsByProtocol/{protocol}`
- [ ] `/delegates/getDelegatedVotingPowerByProtocol/{protocol}`
- [ ] ~~`/delegates/{address}/getDelegatorCount`~~
- [x]  ~~`/getDelegationPitch/{protocol}`~~

### User Data
- [ ] ~~`/userDetails/{address}`~~

**Comment by santteegt** [comment]
This info should be used in #4

**Comment by wtfsayo** [comment]
striked off not-good and irrelevant
