### ISSUE TITLE
2.0.5 Implement Docker Deployment

### ISSUE THREAD

**Issue by santteegt** [raid-guild/gaianet-rag-api-pipeline#30]
Define a docker container setup for the data pipeline application so users can deploy it without dealing with complex configuration and dependency installation in the host machine.

- [x] Define docker file
- [ ] Define volumes
- [x] Define network config to connect with gaia node
- [ ] Update README with setup instructions

Resources:
- https://pathway.com/developers/user-guide/deployment/docker-deployment

**Comment by earth2travis** [comment]
Relates to: https://github.com/raid-guild/gaianet-rag-api-pipeline/issues/1

**Comment by santteegt** [comment]
Add `qdrant/qdrant` image to the dev docker-compose. It should have the following ports and volumes:

```
docker run -p 6333:6333 -p 6334:6334 \
    -v $(pwd)/qdrant_storage:/qdrant/storage:z \
    qdrant/qdrant:v1.10.1
```

special emphasis on the image version (the same as gaia use)
