### ISSUE TITLE
2.2.2 Implement tests

### ISSUE THREAD

**Issue by santteegt** [raid-guild/gaianet-rag-api-pipeline#31]
Implement tests with offline data snippets.

Resources:
- https://pathway.com/developers/user-guide/deployment/integration/#easy-testing-and-cicd

**Comment by earth2travis** [comment]
Manual testing has been completed in:

- https://github.com/raid-guild/gaianet-rag-api-pipeline/issues/21
- https://github.com/raid-guild/gaianet-rag-api-pipeline/issues/28
- https://github.com/raid-guild/gaianet-rag-api-pipeline/issues/33

Implementing automated testing is outside the scope of the current project but should be added in a future enhancement
