### ISSUE TITLE
Identify another API source and Test Rag Pipeline

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#33]
Integrate the OpenAPI specification into the pipeline entrypoints to support dynamic API interactions. Additionally, a new API will be selected and integrated to test the pipeline's flexibility, focusing on one that uses different authentication and pagination methods. The goal is to ensure the pipeline can extract, process, and generate accurate outputs from diverse data sources.

**Comment by earth2travis** [comment]
## Possible APIs

- Gitcoin Grants
- [Agora's OP API](https://vote.optimism.io/api_v1)

Criteria:
- Different pagination method
- Different Auth/API key method

**Comment by wtfsayo** [comment]
identified endpoints for OP Agora

- [ ] /delegates (238,881 records!!!)
- ~~[ ] /delegates/{addressOrEns}~~
- ~~[ ] /delegates/{addressOrEns}/votes~~
- ~~[ ] /delegates/{addressOrEns}/delegatees~~
- ~~[ ] /delegates/{addressOrEns}/delegators~~
-------
- [ ] /proposals
- ~~[ ] /proposals/{proposalId}~~
- ~~[ ] /proposal/{proposalId}/votes~~
-------
- [ ] /retrofunding/rounds/:roundId/projects
- [ ] /projects

**Comment by santteegt** [comment]
@wtfsayo could you generate an openAPI spec for the agora API?

**Comment by wtfsayo** [comment]
> @wtfsayo could you generate an openAPI spec for the agora API?

Sure let's create ticket for it @earth2travis 

edit: Created #37
