### ISSUE TITLE
Create API Schema file for selected Agora Optimism APIs

### ISSUE THREAD

**Issue by wtfsayo** [raid-guild/gaianet-rag-api-pipeline#37]
identified endpoints for OP Agora

- [x] /delegates
- [x] /delegates/{addressOrEns}
- [x] /delegates/{addressOrEns}/votes
- [x] /delegates/{addressOrEns}/delegatees
- [x] /delegates/{addressOrEns}/delegators
-------
- [x] /proposals
- [x] /proposals/{proposalId}
- [x] /proposal/{proposalId}/votes

**Comment by earth2travis** [comment]
Related to: https://github.com/raid-guild/gaianet-rag-api-pipeline/issues/33

**Comment by wtfsayo** [comment]
@santteegt pushed to main! do test!
