### ISSUE TITLE
Deploy a Gaia Node Cloud Instance

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#38]
Deploy a cloud instance to host the Gaia node for enhanced scalability and stability.

- [ ] Determine the necessary hardware requirements to handle the data load
- [ ] Select a cloud vendor based on cost, performance, and compatibility
- [ ] Verify the Gaia node configuration on new infrastructure

## Enterprise General System Requirements

Operating System: Windows need WSL, Mac, Linux
GPU: 12GB (Nvidia or Apple Silicon), AMD not yet supported
Processor: 4 vCPUs (g4dn.xlarge runs well)
RAM: 16GB
Storage: 20GB (Depending on the model you want to use)
Network: Internet

## Recommended Specifications

CPU: Intel Core i7 or AMD Ryzen 7 or equivalent (64-bit)
RAM: 32-64GB
Storage: 1TB SSD
GPU: NVIDIA GeForce RTX 3070 or equivalent

**Comment by santteegt** [comment]
superseded by #40 but need to consider it if the client request us to keep a node running
