### ISSUE TITLE
1.3 Normalize Data

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#7]
Normalize the extracted data to ensure consistency and compatibility with the target data schema. Normalization involves transforming the data into a standard format, addressing any discrepancies or variations in the raw data. This process is essential for maintaining data integrity and facilitating accurate analysis.

- [X] Implement data normalization transform function based on data analysis from the partition stage

**Comment by earth2travis** [comment]
First version in place

**Comment by santteegt** [comment]
Need to re-evaluate the current strategy. Potential adjustments:
- Concatenate long-form texts prior to partitioning
- Eval OpenAPI spec to classify long-form texts and quantitative/qualitative metadata fields

**Comment by santteegt** [comment]
To consider in #22 
- Metadata as JSON or converted into a markdown table
