### ISSUE TITLE
1.5 Implement Intermediate Data Store

### ISSUE THREAD

**Issue by earth2travis** [raid-guild/gaianet-rag-api-pipeline#8]
Setup an intermediate data store to temporarily hold the transformed data before it is transferred to the final storage or embedding system. The intermediate data store acts as a buffer, allowing for efficient data processing and management. This step is crucial for handling large volumes of data and ensuring smooth data flow within the pipeline.

- [] Define data store solution
- [X] Define output format

**Comment by santteegt** [comment]
Currently, intermediate data is stored locally in `jsonl` format

**Comment by santteegt** [comment]
pyairbyte offers some catching solutions during data extraction. We might end up using it for our purposes

**Comment by santteegt** [comment]
To consider in #29 :
- Define specific folders for different intermediate data stores
  -  DuckDB for caching data extraction
  - JSONL files for partitioned/chunked data
